name: flight_search
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NothingYouCouldDo
      fonts:
        - asset: fonts/NothingYouCouldDo.ttf